# Numpy

> Reference Matrial: 
> https://numpy.org/devdocs/user/quickstart.html#advanced-indexing-and-index-tricks

### Assigning to arrays

In [2]:
import numpy as np
A=np.arange(1,28).reshape(3,3,3)

In [71]:
# You can assign an element
A[0][0][0]=-10
A[0,1,2] = -100
print(A)

[[[ -10    2    3]
  [   4    5 -100]
  [   7    8    9]]

 [[  10   11   12]
  [  13   14   15]
  [  16   17   18]]

 [[  19   20   21]
  [  22   23   24]
  [  25   26   27]]]


In [5]:
# You can also assign a subarray by slicing

# The value can be an array of the same shape
A[0,:,:]=np.arange(-9,0).reshape(3,3) # Equivalent to A[0]
A[1]=np.arange(-18,-9).reshape(3,3)
print(A)

[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-15 -14 -13]
  [-12 -11 -10]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]]]


In [7]:
# The value can be a constant
A[1,1,:]=-50
print(A)
print('*'*10)

[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-50 -50 -50]
  [-12 -11 -10]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]]]
**********


In [13]:
print(A[1])
print(A[0])
print(A[ [0,1] ])
print('-'*50)
print(A)

[[-18 -17 -16]
 [-50 -50 -50]
 [-12 -11 -10]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-50 -50 -50]
  [-12 -11 -10]]]
--------------------------------------------------
[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-50 -50 -50]
  [-12 -11 -10]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]]]


In [29]:
# The value can also be a subarray that can be broadcasted
A=np.arange(1,28).reshape(3,3,3)

#A[2,:]=np.arange(1,4)
#A[[1,2]]=np.arange(1,4) #A[1] = np.ara  and A[2] = np.ara
A[[1,2], [0,1], :]=np.arange(1,4)
A[[0,2],[1,2],[0,1]] = -90000
A[[0,2],[1,2],2] = -9999
print(A)


[[[     1      2      3]
  [-90000      5  -9999]
  [     7      8      9]]

 [[     1      2      3]
  [    13     14     15]
  [    16     17     18]]

 [[    19     20     21]
  [     1      2      3]
  [    25 -90000  -9999]]]


In [41]:
a = np.arange(12)**2                       # the first 12 square numbers
print(a)
#i = np.array([1, 1, 3, 8, 5])              # an array of indices
#print(a[i])                                      # the elements of a at the positions i
#print(a[[3,4]])

j = np.array([[3, 4], [9, 7],[8,8],[8,8]])      # a bidimensional array of indices
print(a[j])                        # the same shape as j
print(a[j].shape)
print(a)
print(a.shape)


[  0   1   4   9  16  25  36  49  64  81 100 121]
[[ 9 16]
 [81 49]
 [64 64]
 [64 64]]
(4, 2)
[  0   1   4   9  16  25  36  49  64  81 100 121]
(12,)


### Integer Indexing

In [42]:
A=np.arange(1,65).reshape(4,4,4)

In [43]:
# You can index an array with a list/array of indices
print(A)
print(A[[0,1]])
print("\n"+"-_"*20+"\n")

# Just a single array indexes the first dimension, same as

print(A[[0,1],:,:])
print("\n"+"-_"*20+"\n")

# You can also index the other dimensions
print(A[:,:,[0,2]])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[[[ 1  3]
  [ 5  7]
  [ 9 11]
  [13 15]]

 [[17 19]
  [21 23]
  [25 27]
  [29 31]]

 [[33 35]
  [37 39]
  [41 43]
  [45 47]]

 [[49 51]
  [53 55]
  [57 59]
  [61 63]]]


In [44]:
# You can repeat an index in your array

print(A[[0,1,0,0,1],:,:])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]


In [54]:
# You can give a list of indexes for each dimension
print(A[[0,1,0,0],
        [1,2,2,2],
        [0,1,2,3]])

[ 5 26 11 12]


In [58]:
# The list of indices can be in a more complicated shape
print(A)
i=np.array([[0,1],[1,0]])
j=np.array([[1,2],[2,2]])
k=np.array(       [1,2])  #=> [[1,2],[1,2]]
A[i,j,k]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


array([[ 6, 27],
       [26, 11]])

In [65]:
# Shuffle an array
A=np.random.randint(1,20,10)
print(A)
shuffle=np.random.permutation(A.shape[0]) #np.random.shuffle(np.arange(number))
print(shuffle)
print(A[shuffle]) #np.random.shuffle(A)

[14 13  9  4 19  2  5 15 10 11]
[0 3 9 4 1 6 7 5 8 2]
[14  4 11 19 13  5 15  2 10  9]


In [66]:
# Sort an array according to another array

A=np.random.randint(1,20,10)
B=np.random.randint(1,20,10)

sorted_idcs=np.argsort(A)
B_sorted=B[sorted_idcs]

In [67]:
# You can also assign using integer indices

A=np.arange(1,28).reshape(3,3,3)
print(A)
A[[1,2],[0,2],2]=-50

print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  11 -50]
  [ 13  14  15]
  [ 16  17  18]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26 -50]]]


In [69]:
a = np.arange(12).reshape(3,4)
print(a)
print(a[[[0,1],[1,2]], [[2, 1],[3, 3]]])


i = np.array([[0, 1],[1, 2]])                     # indices for the first dim of a
              
j = np.array([[2, 1],[3, 3]])                     # indices for the second dim
              

print(a[i, j])                                   # i and j must have equal shape
print(a[i,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  5]
 [ 7 11]]
[[ 2  5]
 [ 7 11]]
[[ 2  6]
 [ 6 10]]


### Boolean Indexing

In [80]:
A=np.random.randint(1,50,12).reshape(3,4)
print(A)


[[45 13 45 31]
 [10 38 45 21]
 [ 8 42 48 13]]


In [81]:
# You can do slices or selections using boolean arrays same length as the dimension
# This is recommended to do only for one dimension

# selecting rows
#print(A[[True,True,True],:])
print("\n"+"-_"*20+"\n")

# selecting columns
#print(A[:,[True,False,False,True]])
print("\n"+"-_"*20+"\n")

# selecting both rows and columns is confusing
# and not recommended

print(A[[True,False,True],[True,False,False,True]])


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[45 13]


In [85]:
# Generally you'll use this in a more complicated way
# For example let's get the rows that have maximums > some value

A=np.random.randint(0,50,(4,6))
print(A)
print("\n"+"-_"*20+"\n")

maxes=np.max(A,axis=1)
print(maxes)
print(maxes>40)
print("\n"+"-_"*20+"\n")

print(A[maxes>40,:])

#np.where(condition, true_case, false_case)

[[ 1  9 44 25 10 32]
 [28 26 34 40  5  1]
 [27 25  0  0 42 29]
 [38  9 12 21 23 16]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[44 40 42 38]
[ True False  True False]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[[ 1  9 44 25 10 32]
 [27 25  0  0 42 29]]


In [87]:
# You can also index by a boolean array of the size as the 
# original
# It gives a flat array with all the entries that had True
print(A>10)
print(A[A>10])

[[False False  True  True False  True]
 [ True  True  True  True False False]
 [ True  True False False  True  True]
 [ True False  True  True  True  True]]
[44 25 32 28 26 34 40 27 25 42 29 38 12 21 23 16]


In [89]:
# Again you can use Boolean indexing to assign values

A=np.random.randint(0,50,(4,6))
print(A)
print("\n"+"-_"*20+"\n")
print(A[:,0])
A[A[:,0]<30]=np.arange(-6,0)
print(A)

[[32 40 33 13 25 37]
 [ 4 16 34 25 30 34]
 [ 2 26 47 30 34 19]
 [31 12 22 38 20 16]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[32  4  2 31]
[[32 40 33 13 25 37]
 [-6 -5 -4 -3 -2 -1]
 [-6 -5 -4 -3 -2 -1]
 [31 12 22 38 20 16]]


### np.inf, np.nan

In [92]:
# Numpy has a special type to represent infinity

print(np.inf)

# Actually regular python also has infinity

print(float("inf"))

inf
inf


In [94]:
# Let's see how np.inf behaves

# Multiplying by a negative number gives -np.inf
x=np.inf
print(x)
x*=-1
print(x)

# The opposite also works

x*=-5
print(x)

inf
-inf
inf


In [95]:
# Adding,subtracting,dividing,multiplying with normal
# numbers gives np.inf ( or -np.inf) except when multiplying
# or dividing with a negative number

print(np.inf+5)
print(-np.inf-6)
print(-np.inf*-30)
print(-np.inf/-22)

inf
-inf
inf
inf


In [97]:
# Dividing a number by np.inf gives 0

print(1223/np.inf)

0.0


In [98]:
# Interestingly dividing by 0 in numpy arrays gives infinity

print(np.array([222])/0)

[inf]


<ipython-input-98-067a3885ebda>:3: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([222])/0)


In [102]:
# What about operations between np.inf

# These have some meaning
print(np.inf + np.inf)
print(np.inf*np.inf)

# These are absolutely meaningless
print(np.inf-np.inf)
print(np.inf/np.inf)

inf
inf
nan
nan


In [103]:
# Which brings us to another special numpy data type
# nan : Not a Number
print(np.nan)

# Numpy uses nan to designate invalid values
# You can use it too

print(np.array([1,1,np.nan,2]))

nan
[ 1.  1. nan  2.]


In [105]:
# Some other ways you can get np.nan

print(np.sqrt(-2))
print(np.zeros(1)/np.zeros(1))
print(np.inf * 0)
print(np.log(-2))

nan
[nan]
nan
nan


<ipython-input-105-5512382ab81e>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-2))
<ipython-input-105-5512382ab81e>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.zeros(1)/np.zeros(1))
<ipython-input-105-5512382ab81e>:6: RuntimeWarning: invalid value encountered in log
  print(np.log(-2))


In [106]:
# Any operation with np.nan gives np.nan

print(1+np.nan)
print(np.inf + np.nan)
print(np.nan/np.array([0]))
print(np.nan - np.nan)

nan
nan
[nan]
nan


In [107]:
print(100/0)

ZeroDivisionError: division by zero

1. There might be some valid use cases for np.inf, but mostly you will encounter it when some calculation error happens - similar to division by zero.
2. If you see np.nan then clearly some undefined arithmetic operation has happened in your code. 

# Pandas

* Pandas is a library for analysing tabular data. It's the sort of analysis you would do on Excel, or using SQL.
* Numpy is about arrays of homogeneous data, Pandas is about columns of homogeneous data, but overall arranged in a table. 
* Pandas provides objects like DataFrame and GroupBy, which expose methods that allow us to make complex queries in an easy to understand manner.

> Resources :  
> [10 Minutes to Pandas Tutorial](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html#min)  
> [Other tutorials](https://pandas.pydata.org/pandas-docs/stable/getting_started/tutorials.html)  
> [The User Guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)  
> [The API reference](https://pandas.pydata.org/pandas-docs/stable/reference/index.html)  
> [Source](https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/)

In [89]:
import pandas as pd
import numpy as np

## The DataFrame object

In [90]:
# Let's read a CSV and create a DataFrame object from it
# And then let us examine some of its properties
with open("pandas_demo.csv","r") as fi:
    df=pd.read_csv(fi)

In [91]:
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


first_name      last_name                       email  gender  \
0         Otha         Gjerde      ogjerde0@biglobe.ne.jp  Female   
1        Yance      Barnsdale   ybarnsdale1@reference.com    Male   
2      Lazarus        MacNish    lmacnish2@altervista.org    Male   
3       Monroe        Gwinnel       mgwinnel3@booking.com    Male   
4      Gaspard      Gullivent       ggullivent4@wikia.com    Male   
..         ...            ...                         ...     ...   
995     Eduino  Alessandretti  ealessandrettirn@topsy.com    Male   
996   Vivianna            Rix              vrixro@sun.com  Female   
997    Donaugh         Emmert          demmertrp@sohu.com    Male   
998   Reinaldo     O'Scannill      roscannillrq@desdev.cn    Male   
999  Justinian          Goney  jgoneyrr@deliciousdays.com    Male   

          employer                     designation  \
0           Zomato                             NaN   
1    Goldman Sachs                   Social Worker   
2              TCS          Administrative Officer   
3    Goldman Sachs                Technical Writer   
4          Infosys             Clinical Specialist   
..             ...                             ...   
995        Infosys             Structural Engineer   
996       Flipkart                Quality Engineer   
997         Google              Recruiting Manager   
998       Flipkart              VP Quality Control   
999       Flipkart  Payment Adjustment Coordinator   

                                       university personal_phone      bank  \
0                           Sang Myung University   132-421-9138      HDFC   
1            Fachhochschule Ravensburg-Weingarten   492-125-1131       SBI   
2    California State University, Channel Islands   235-492-4252     ICICI   
3                   St. Mary-of-the-Woods College            NaN     ICICI   
4                 Islamic Azad University, Quchan   232-527-4054     ICICI   
..                                            ...            ...       ...   
995                     Universidad Adolfo Ibáñez   354-283-0381     ICICI   
996                             Stonehill College   785-322-0735  Yes Bank   
997        University of the South Pacific Centre   585-826-1040      HDFC   
998                      Bulacan State University   268-203-9762     ICICI   
999                            Arcadia University   173-701-0038  Yes Bank   

     birth_year  years_employed  
0          1970            24.0  
1          1960            32.0  
2          1970            24.0  
3          1982            14.4  
4          1998             1.6  
..          ...             ...  
995        1978            17.6  
996        1990             8.0  
997        1962            30.4  
998        1990             8.0  
999        1978            17.6  

[1000 rows x 11 columns]

In [20]:
df.head(6)

first_name  last_name                     email  gender       employer  \
0      Merle    Kenelin        mkenelin0@tamu.edu    Male          Aivee   
1   Marigold    Haddock    mhaddock1@illinois.edu  Female      Realpoint   
2      Nessy  Restorick       nrestorick2@com.com  Female          Npath   
3    Madella   Lantuffe    mlantuffe3@comcast.net  Female  Thoughtbridge   
4        Bax   Chaudron     bchaudron4@reddit.com    Male     Shuffletag   
5    Yehudit   Schroder  yschroder5@tuttocitta.it    Male     Browsetype   

                     designation  \
0               Dental Hygienist   
1               Technical Writer   
2                    Engineer IV   
3  Analog Circuit Design manager   
4          VP Product Management   
5         Senior Sales Associate   

                                         university personal_phone  \
0                      Concordia University, Irvine   158-563-8593   
1  Universidad Michoacana de San Nicolás de Hidalgo   209-273-8218   
2                                               NaN   530-775-4072   
3               California State University, Fresno            NaN   
4   Institute of Management and Business Technology   824-449-7742   
5                         Universidad de Cienfuegos   530-514-8363   

     credit_card  birth_year  years_employed  
0  visa-electron        1996             3.2  
1            jcb        1997             2.4  
2  visa-electron        1977            18.4  
3            NaN        1982            14.4  
4            jcb        1981            15.2  
5            jcb        1991             7.2

In [21]:
df.tail(3)

first_name    last_name                        email  gender     employer  \
997       Tana  Weatherhogg    tweatherhoggrp@flickr.com  Female       Tekfly   
998    Mikaela     Raycroft  mraycroftrq@kickstarter.com  Female  Thoughtblab   
999   Jeanette       Korpal        jkorpalrr@dropbox.com  Female       Agimba   

          designation                               university personal_phone  \
997           Actuary       Universitas Wijaya Kusuma Surabaya            NaN   
998      Developer II             University of Maine, Augusta   276-706-4994   
999  Senior Developer  Universidad Argentina "John F. Kennedy"            NaN   

             credit_card  birth_year  years_employed  
997                  NaN        1981            15.2  
998  diners-club-enroute        1994             4.8  
999                  NaN        1988             9.6

In [22]:
df.columns

Index(['first_name', 'last_name', 'email', 'gender', 'employer', 'designation',
       'university', 'personal_phone', 'credit_card', 'birth_year',
       'years_employed'],
      dtype='object')

In [23]:
df.dtypes

first_name         object
last_name          object
email              object
gender             object
employer           object
designation        object
university         object
personal_phone     object
credit_card        object
birth_year          int64
years_employed    float64
dtype: object

In [25]:
df.describe()

birth_year  years_employed
count  1000.000000     1000.000000
mean   1978.807000       16.954400
std      11.341887        9.073509
min    1960.000000        1.600000
25%    1969.000000        8.800000
50%    1979.000000       16.800000
75%    1989.000000       24.800000
max    1998.000000       32.000000

In [26]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [27]:
df.values

array([['Merle', 'Kenelin', 'mkenelin0@tamu.edu', ..., 'visa-electron',
        1996, 3.2],
       ['Marigold', 'Haddock', 'mhaddock1@illinois.edu', ..., 'jcb',
        1997, 2.4],
       ['Nessy', 'Restorick', 'nrestorick2@com.com', ...,
        'visa-electron', 1977, 18.4],
       ...,
       ['Tana', 'Weatherhogg', 'tweatherhoggrp@flickr.com', ..., nan,
        1981, 15.2],
       ['Mikaela', 'Raycroft', 'mraycroftrq@kickstarter.com', ...,
        'diners-club-enroute', 1994, 4.8],
       ['Jeanette', 'Korpal', 'jkorpalrr@dropbox.com', ..., nan, 1988,
        9.6]], dtype=object)

In [274]:
# You can create the dataframe object using the pd.DataFrame() constructor
# Here is one way

a=pd.DataFrame(index=range(0,10),columns=["A","B","C"],data=np.random.randint(1,10,(10,3)))
display(a)

A  B  C
0  1  1  2
1  4  6  2
2  5  3  8
3  4  8  6
4  4  9  5
5  4  4  4
6  2  5  1
7  9  8  5
8  9  4  3
9  2  7  9

## Reading data

### The main interface

In [29]:
# Columns can be accessed using dot notation
df.birth_year

0      1996
1      1997
2      1977
3      1982
4      1981
       ... 
995    1975
996    1977
997    1981
998    1994
999    1988
Name: birth_year, Length: 1000, dtype: int64

In [34]:
# Columns can also be indexed - This will return a series
df["birth_year"]

0      1996
1      1997
2      1977
3      1982
4      1981
       ... 
995    1975
996    1977
997    1981
998    1994
999    1988
Name: birth_year, Length: 1000, dtype: int64

In [38]:
# Multiple columns can also be indexed - This will return a DataFrame
df[["first_name","birth_year"]]

first_name  birth_year
0        Merle        1996
1     Marigold        1997
2        Nessy        1977
3      Madella        1982
4          Bax        1981
..         ...         ...
995   Christye        1975
996    Beltran        1977
997       Tana        1981
998    Mikaela        1994
999   Jeanette        1988

[1000 rows x 2 columns]

In [54]:
# You can slice the rows by position
sliced=df[50:100]
# Note that the index still keeps the old numbers
# Thus index itself is kind of like a series - it's not just numbering from top to bottom.
# Actually, the index can be strings, dates anything
# Though for simplicity we will stick to integer indexes
print(sliced.index)
sliced.head()

RangeIndex(start=50, stop=100, step=1)


first_name  last_name                       email  gender     employer  \
50    Ceciley    Breakey   cbreakey1e@slideshare.net  Female      Camimbo   
51     Walliw        Ley             wley1f@java.com  Female    Photofeed   
52        Tod   McInteer  tmcinteer1g@shareasale.com    Male       Tambee   
53   Charmine     Hearon       chearon1h@harvard.edu  Female  Topiclounge   
54      Rikki  Verbrugge     rverbrugge1i@usnews.com    Male         Geba   

                 designation  \
50  Systems Administrator IV   
51   Human Resources Manager   
52       Software Consultant   
53     Chief Design Engineer   
54   Systems Administrator I   

                                           university personal_phone  \
50  Instituto Superior de Relações Internacionais ...   269-104-0079   
51              Massachusetts Institute of Technology   363-227-4335   
52                                                NaN   727-221-1362   
53                                 Manchester College   478-235-7826   
54         State Pedagogical University in Kryvyi Rih   111-278-6472   

   credit_card  birth_year  years_employed  
50         jcb        1985            12.0  
51         jcb        1985            12.0  
52       laser        1980            16.0  
53       laser        1984            12.8  
54    bankcard        1982            14.4

In [53]:
# You can chain the two indexing style
df[:50][["first_name","last_name"]].head(5)

first_name  last_name
0      Merle    Kenelin
1   Marigold    Haddock
2      Nessy  Restorick
3    Madella   Lantuffe
4        Bax   Chaudron

To summarise, indexing the dataframe directly like ``df[]`` allows
* indexing a single column by name (or label)
* indexing a list of columns by name 
* slicing of rows by position.

Note that the following things doesn't work
* indexing columns by position
* indexing/slicing rows by name/label

As we will see, there are two other interfaces that give us this functionality.

### .loc

In [57]:
# Index a column by name same as before
# Notice that now you have to compulsarily provide a slice for the rows
df.loc[:,["first_name","last_name"]]

first_name    last_name
0        Merle      Kenelin
1     Marigold      Haddock
2        Nessy    Restorick
3      Madella     Lantuffe
4          Bax     Chaudron
..         ...          ...
995   Christye      Boreham
996    Beltran         Elvy
997       Tana  Weatherhogg
998    Mikaela     Raycroft
999   Jeanette       Korpal

[1000 rows x 2 columns]

In [59]:
# But let's look at rows
sliced=df[50:100]
# Note the index goes from 50 to 100
sliced.head()

first_name  last_name                       email  gender     employer  \
50    Ceciley    Breakey   cbreakey1e@slideshare.net  Female      Camimbo   
51     Walliw        Ley             wley1f@java.com  Female    Photofeed   
52        Tod   McInteer  tmcinteer1g@shareasale.com    Male       Tambee   
53   Charmine     Hearon       chearon1h@harvard.edu  Female  Topiclounge   
54      Rikki  Verbrugge     rverbrugge1i@usnews.com    Male         Geba   

                 designation  \
50  Systems Administrator IV   
51   Human Resources Manager   
52       Software Consultant   
53     Chief Design Engineer   
54   Systems Administrator I   

                                           university personal_phone  \
50  Instituto Superior de Relações Internacionais ...   269-104-0079   
51              Massachusetts Institute of Technology   363-227-4335   
52                                                NaN   727-221-1362   
53                                 Manchester College   478-235-7826   
54         State Pedagogical University in Kryvyi Rih   111-278-6472   

   credit_card  birth_year  years_employed  
50         jcb        1985            12.0  
51         jcb        1985            12.0  
52       laser        1980            16.0  
53       laser        1984            12.8  
54    bankcard        1982            14.4

In [60]:
# We can index by position with the main interface - for example : 0:5 returns 50-54
sliced[0:5]

first_name  last_name                       email  gender     employer  \
50    Ceciley    Breakey   cbreakey1e@slideshare.net  Female      Camimbo   
51     Walliw        Ley             wley1f@java.com  Female    Photofeed   
52        Tod   McInteer  tmcinteer1g@shareasale.com    Male       Tambee   
53   Charmine     Hearon       chearon1h@harvard.edu  Female  Topiclounge   
54      Rikki  Verbrugge     rverbrugge1i@usnews.com    Male         Geba   

                 designation  \
50  Systems Administrator IV   
51   Human Resources Manager   
52       Software Consultant   
53     Chief Design Engineer   
54   Systems Administrator I   

                                           university personal_phone  \
50  Instituto Superior de Relações Internacionais ...   269-104-0079   
51              Massachusetts Institute of Technology   363-227-4335   
52                                                NaN   727-221-1362   
53                                 Manchester College   478-235-7826   
54         State Pedagogical University in Kryvyi Rih   111-278-6472   

   credit_card  birth_year  years_employed  
50         jcb        1985            12.0  
51         jcb        1985            12.0  
52       laser        1980            16.0  
53       laser        1984            12.8  
54    bankcard        1982            14.4

In [61]:
# But can we slice with respect to the original index?

# This will return an empty DF, as position is only upto 50
sliced[55:60]

Empty DataFrame
Columns: [first_name, last_name, email, gender, employer, designation, university, personal_phone, credit_card, birth_year, years_employed]
Index: []

In [63]:
# But this works well
sliced.loc[55:60]

first_name last_name                          email  gender      employer  \
55     Ulrica  Widdison             uwiddison1j@va.gov  Female      Edgeblab   
56       Gael   Paddock           gpaddock1k@yahoo.com    Male        Trilia   
57     Kelwin   Goodger           kgoodger1l@github.io    Male       Yakidoo   
58     Rustin    Jeffes          rjeffes1m@archive.org    Male  Jabbersphere   
59     Barris   Kiossel          bkiossel1n@ebay.co.uk    Male      Feedfish   
60    Dulcine  Coughlin  dcoughlin1o@blogtalkradio.com  Female       Meembee   

                     designation  \
55                       Actuary   
56            Speech Pathologist   
57              Product Engineer   
58  Structural Analysis Engineer   
59    Physical Therapy Assistant   
60                  VP Marketing   

                                         university personal_phone  \
55                     Universidade Gregorio Semedo   132-476-4488   
56                                    Touro College   565-720-1987   
57                           University of Belgrade            NaN   
58               Ecole Normale Supérieure de Cachan   211-888-9536   
59  State University of New York College at Geneseo   340-166-6123   
60                            University of Trieste   159-922-2968   

            credit_card  birth_year  years_employed  
55  diners-club-enroute        1990             8.0  
56              maestro        1960            32.0  
57                  NaN        1987            10.4  
58                 visa        1989             8.8  
59                  jcb        1979            16.8  
60                  jcb        1961            31.2

In [64]:
# Sometimes the original index is useful, especially if you want to modify the slice
# and assign to the original DataFrame (it automatically matches the indexes)

# But sometimes after a slice you want to reset the index
sliced=sliced.reset_index()
sliced

index  first_name   last_name                             email  gender  \
0      50     Ceciley     Breakey         cbreakey1e@slideshare.net  Female   
1      51      Walliw         Ley                   wley1f@java.com  Female   
2      52         Tod    McInteer        tmcinteer1g@shareasale.com    Male   
3      53    Charmine      Hearon             chearon1h@harvard.edu  Female   
4      54       Rikki   Verbrugge           rverbrugge1i@usnews.com    Male   
5      55      Ulrica    Widdison                uwiddison1j@va.gov  Female   
6      56        Gael     Paddock              gpaddock1k@yahoo.com    Male   
7      57      Kelwin     Goodger              kgoodger1l@github.io    Male   
8      58      Rustin      Jeffes             rjeffes1m@archive.org    Male   
9      59      Barris     Kiossel             bkiossel1n@ebay.co.uk    Male   
10     60     Dulcine    Coughlin     dcoughlin1o@blogtalkradio.com  Female   
11     61        Jeth     Dawbery                 jdawbery1p@nhs.uk    Male   
12     62     Suellen    Rubertis         srubertis1q@instagram.com  Female   
13     63   Jeannette    Britzius         jbritzius1r@123-reg.co.uk  Female   
14     64    Theobald     Crookes               tcrookes1s@admin.ch    Male   
15     65        Rufe     Milsted               rmilsted1t@etsy.com    Male   
16     66     Phillip     Cristou             pcristou1u@cpanel.net    Male   
17     67     Gusella      Ondrus             gondrus1v@cornell.edu  Female   
18     68      Carlin     Carreck              ccarreck1w@nifty.com  Female   
19     69  Maximilien     Marsham            mmarsham1x@samsung.com    Male   
20     70         Lib    Snassell              lsnassell1y@sohu.com  Female   
21     71        Lind      Loghan              lloghan1z@eepurl.com  Female   
22     72      Jemima      Horrod                  jhorrod20@cbc.ca  Female   
23     73      Krysta      Yanson              kyanson21@dion.ne.jp  Female   
24     74        Dell      Inmett               dinmett22@imgur.com  Female   
25     75      Shandy  De Andisie          sdeandisie23@samsung.com  Female   
26     76   Brunhilda     Espinoy           bespinoy24@virginia.edu  Female   
27     77      Elijah   MacConnel          emacconnel25@addthis.com    Male   
28     78    Gloriane    Linneman  glinneman26@networksolutions.com  Female   
29     79       Judon     Prudham           jprudham27@illinois.edu    Male   
30     80       Corry    McArdell               cmcardell28@icq.com  Female   
31     81      Ericka      Brason           ebrason29@moonfruit.com  Female   
32     82       Brian    Domesday               bdomesday2a@unc.edu    Male   
33     83     Arlinda        Peek                      apeek2b@g.co  Female   
34     84       Robyn      Ventam            rventam2c@cbslocal.com  Female   
35     85       Donni      Pagden                 dpagden2d@com.com  Female   
36     86       Berry     Grocott             bgrocott2e@toplist.cz  Female   
37     87      Barbra     Gilyatt     bgilyatt2f@huffingtonpost.com  Female   
38     88       Berri       Milan             bmilan2g@bandcamp.com  Female   
39     89        Wang  Malletratt        wmalletratt2h@virginia.edu    Male   
40     90       Orion    Shevlane               oshevlane2i@unc.edu    Male   
41     91      Joelly    Aucourte             jaucourte2j@lycos.com  Female   
42     92       Vania     Peschet               vpeschet2k@1und1.de  Female   
43     93     Wrennie      Melody     wmelody2l@creativecommons.org  Female   
44     94    Jermaine      Peploe                 jpeploe2m@soup.io  Female   
45     95     Rosanne    Goodburn           rgoodburn2n@youtube.com  Female   
46     96     Viviyan     Refford           vrefford2o@bandcamp.com  Female   
47     97       Cyndy        Lote             clote2p@csmonitor.com  Female   
48     98        Ives     Kersley               ikersley2q@xrea.com    Male   
49     99       Hyman      Belbin                hbelb

### .iloc

In [66]:
# This is good ol' numpy style indexing 
# By position on rows
# and By position on columns
df.iloc[5:7,:3]

first_name     last_name                     email
5    Yehudit      Schroder  yschroder5@tuttocitta.it
6      Jareb  Jakoviljevic   jjakoviljevic6@dmoz.org

In [70]:
# A value
df.iloc[5,1]

'Schroder'

In [72]:
# A series
df.iloc[:5,1]

0      Kenelin
1      Haddock
2    Restorick
3     Lantuffe
4     Chaudron
Name: last_name, dtype: object

In [71]:
# also a series
df.iloc[5,1:6]

last_name                      Schroder
email          yschroder5@tuttocitta.it
gender                             Male
employer                     Browsetype
designation      Senior Sales Associate
Name: 5, dtype: object

In [73]:
df.iloc[:,["first_name"]]

IndexError: .iloc requires numeric indexers, got ['first_name']

### Boolean indexing

In [75]:
# boolean indexing by column
only_90s_kids=df[df.birth_year>=1990]
only_90s_kids=only_90s_kids[only_90s_kids.birth_year<=2000]
print(len(only_90s_kids))
only_90s_kids.head(5)

229


first_name   last_name                     email  gender     employer  \
0       Merle     Kenelin        mkenelin0@tamu.edu    Male        Aivee   
1    Marigold     Haddock    mhaddock1@illinois.edu  Female    Realpoint   
5     Yehudit    Schroder  yschroder5@tuttocitta.it    Male   Browsetype   
35    Karlens      Dubois     kduboisz@bandcamp.com    Male  Shufflebeat   
40    Riordan  Jacobowits    rjacobowits14@lulu.com    Male   Realbridge   

                designation                                        university  \
0          Dental Hygienist                      Concordia University, Irvine   
1          Technical Writer  Universidad Michoacana de San Nicolás de Hidalgo   
5    Senior Sales Associate                         Universidad de Cienfuegos   
35       Recruiting Manager                                   Shorter College   
40  GIS Technical Architect         California State University, Monterey Bay   

   personal_phone    credit_card  birth_year  years_employed  
0    158-563-8593  visa-electron        1996             3.2  
1    209-273-8218            jcb        1997             2.4  
5    530-514-8363            jcb        1991             7.2  
35   615-785-9997            jcb        1996             3.2  
40   568-830-5897            jcb        1991             7.2

## Setting data

In [78]:
# The most common operation : computing a new column based on other columns

only_90s_kids["age"] = 2020 - only_90s_kids.birth_year

# Notice how the index is preserved
only_90s_kids.head(5)

first_name   last_name                     email  gender     employer  \
0       Merle     Kenelin        mkenelin0@tamu.edu    Male        Aivee   
1    Marigold     Haddock    mhaddock1@illinois.edu  Female    Realpoint   
5     Yehudit    Schroder  yschroder5@tuttocitta.it    Male   Browsetype   
35    Karlens      Dubois     kduboisz@bandcamp.com    Male  Shufflebeat   
40    Riordan  Jacobowits    rjacobowits14@lulu.com    Male   Realbridge   

                designation                                        university  \
0          Dental Hygienist                      Concordia University, Irvine   
1          Technical Writer  Universidad Michoacana de San Nicolás de Hidalgo   
5    Senior Sales Associate                         Universidad de Cienfuegos   
35       Recruiting Manager                                   Shorter College   
40  GIS Technical Architect         California State University, Monterey Bay   

   personal_phone    credit_card  birth_year  years_employed  age  
0    158-563-8593  visa-electron        1996             3.2   24  
1    209-273-8218            jcb        1997             2.4   23  
5    530-514-8363            jcb        1991             7.2   29  
35   615-785-9997            jcb        1996             3.2   24  
40   568-830-5897            jcb        1991             7.2   29

In [82]:
# You could even have assigned it to the original df

# but let's copy it first ;)
fresh_df=df.copy()

# All the correct indices will be filled otherwise it will be set as NaN.
# This is one of the use cases of having a separate index object
# vs just position numbering like numpy
fresh_df["age"] = 2020 - only_90s_kids.birth_year
fresh_df

first_name    last_name                        email  gender  \
0        Merle      Kenelin           mkenelin0@tamu.edu    Male   
1     Marigold      Haddock       mhaddock1@illinois.edu  Female   
2        Nessy    Restorick          nrestorick2@com.com  Female   
3      Madella     Lantuffe       mlantuffe3@comcast.net  Female   
4          Bax     Chaudron        bchaudron4@reddit.com    Male   
..         ...          ...                          ...     ...   
995   Christye      Boreham        cborehamrn@rambler.ru  Female   
996    Beltran         Elvy           belvyro@forbes.com    Male   
997       Tana  Weatherhogg    tweatherhoggrp@flickr.com  Female   
998    Mikaela     Raycroft  mraycroftrq@kickstarter.com  Female   
999   Jeanette       Korpal        jkorpalrr@dropbox.com  Female   

          employer                    designation  \
0            Aivee               Dental Hygienist   
1        Realpoint               Technical Writer   
2            Npath                    Engineer IV   
3    Thoughtbridge  Analog Circuit Design manager   
4       Shuffletag          VP Product Management   
..             ...                            ...   
995    Twitterlist              Director of Sales   
996         Skaboo            Software Consultant   
997         Tekfly                        Actuary   
998    Thoughtblab                   Developer II   
999         Agimba               Senior Developer   

                                           university personal_phone  \
0                        Concordia University, Irvine   158-563-8593   
1    Universidad Michoacana de San Nicolás de Hidalgo   209-273-8218   
2                                                 NaN   530-775-4072   
3                 California State University, Fresno            NaN   
4     Institute of Management and Business Technology   824-449-7742   
..                                                ...            ...   
995                                               NaN   469-619-6625   
996              Tabari Institute of Higher Education   124-721-6651   
997                Universitas Wijaya Kusuma Surabaya            NaN   
998                      University of Maine, Augusta   276-706-4994   
999           Universidad Argentina "John F. Kennedy"            NaN   

             credit_card  birth_year  years_employed   age  
0          visa-electron        1996             3.2  24.0  
1                    jcb        1997             2.4  23.0  
2          visa-electron        1977            18.4   NaN  
3                    NaN        1982            14.4   NaN  
4                    jcb        1981            15.2   NaN  
..                   ...         ...             ...   ...  
995                  jcb        1975            20.0   NaN  
996                  jcb        1977            18.4   NaN  
997                  NaN        1981            15.2   NaN  
998  diners-club-enroute        1994             4.8  26.0  
999                  NaN        1988             9.6   NaN  

[1000 rows x 12 columns]

In [87]:
# You can of course set values at a particular position
print(fresh_df.iloc[0,-1]) 
fresh_df.iloc[0,-1]=29
print(fresh_df.iloc[0,-1]) 

29.0
29.0


# Data Investigation Example 1

Let's make a set of questions and then see how we can answer them by using pandas

* Who are the employers?
* What is the employee count of each employer?
* What is the % of Male vs Female employees for each company?
* What is the average age of an employee for each company?
* Which bank is most popular in each company?

In [96]:
df[:]["employer"].drop_duplicates()

0            Zomato
1     Goldman Sachs
2               TCS
4           Infosys
5          Flipkart
31           Google
Name: employer, dtype: object

In [98]:
grps=df.groupby(by="employer")

In [101]:
grps.groups

{'Flipkart': Int64Index([  5,   7,  13,  21,  25,  27,  33,  40,  50,  55,
             ...
             957, 962, 966, 970, 981, 985, 991, 996, 998, 999],
            dtype='int64', length=167),
 'Goldman Sachs': Int64Index([  1,   3,   6,  15,  16,  22,  23,  24,  26,  36,
             ...
             951, 956, 960, 961, 973, 974, 975, 982, 986, 988],
            dtype='int64', length=168),
 'Google': Int64Index([ 31,  34,  43,  60,  62,  64,  68,  69,  70,  75,
             ...
             924, 932, 934, 950, 958, 964, 978, 979, 989, 997],
            dtype='int64', length=186),
 'Infosys': Int64Index([  4,   8,  20,  29,  32,  35,  38,  48,  56,  65,
             ...
             953, 954, 968, 969, 971, 977, 980, 987, 990, 995],
            dtype='int64', length=162),
 'TCS': Int64Index([  2,  18,  19,  30,  39,  42,  45,  51,  53,  54,
             ...
             931, 933, 935, 939, 949, 952, 963, 965, 983, 993],
            dtype='int64', length=168),
 'Zomato': Int64Index([

In [104]:
# Notice that it counts non-empty values
grps.count()

first_name  last_name  email  gender  designation  university  \
employer                                                                       
Flipkart              167        167    167     167          158         155   
Goldman Sachs         168        168    168     168          151         152   
Google                186        186    186     186          175         163   
Infosys               162        162    162     162          155         144   
TCS                   168        168    168     168          163         149   
Zomato                149        149    149     149          137         129   

               personal_phone  bank  birth_year  years_employed  
employer                                                         
Flipkart                  134   167         167             167  
Goldman Sachs             131   168         168             168  
Google                    146   186         186             186  
Infosys                   120   162         162             162  
TCS                       139   168         168             168  
Zomato                    113   149         149             149

In [109]:
# So how to get the number of rows in each group?

# One way:
fresh=df.copy()
fresh["id"]=np.arange(0,len(fresh))
display(fresh.groupby("employer").count()["id"])

# Another simpler way :)
display(grps.size())

# Remember a little creativity goes a long way

employer
Flipkart         167
Goldman Sachs    168
Google           186
Infosys          162
TCS              168
Zomato           149
Name: id, dtype: int64

employer
Flipkart         167
Goldman Sachs    168
Google           186
Infosys          162
TCS              168
Zomato           149
dtype: int64

In [123]:
grps=df.groupby(by=["employer","gender"])

# This is an example of a hierarchical index for a series
display(grps.size())

employer       gender
Flipkart       Female    86
               Male      81
Goldman Sachs  Female    85
               Male      83
Google         Female    91
               Male      95
Infosys        Female    82
               Male      80
TCS            Female    92
               Male      76
Zomato         Female    72
               Male      77
dtype: int64

In [124]:
counts=pd.DataFrame(grps.size())
print(counts.to_records())
counts=pd.DataFrame(counts.to_records())
display(counts)

[('Flipkart', 'Female', 86) ('Flipkart', 'Male', 81)
 ('Goldman Sachs', 'Female', 85) ('Goldman Sachs', 'Male', 83)
 ('Google', 'Female', 91) ('Google', 'Male', 95) ('Infosys', 'Female', 82)
 ('Infosys', 'Male', 80) ('TCS', 'Female', 92) ('TCS', 'Male', 76)
 ('Zomato', 'Female', 72) ('Zomato', 'Male', 77)]


employer  gender   0
0        Flipkart  Female  86
1        Flipkart    Male  81
2   Goldman Sachs  Female  85
3   Goldman Sachs    Male  83
4          Google  Female  91
5          Google    Male  95
6         Infosys  Female  82
7         Infosys    Male  80
8             TCS  Female  92
9             TCS    Male  76
10         Zomato  Female  72
11         Zomato    Male  77

In [126]:
with_age=df.copy()
with_age["age"]=2020 - with_age.birth_year
with_age[["employer","age"]].groupby("employer").mean()

age
employer                
Flipkart       41.616766
Goldman Sachs  41.047619
Google         43.000000
Infosys        42.382716
TCS            39.005952
Zomato         42.651007

In [144]:
temp=df[["employer","bank"]].groupby(["employer","bank"]).size()
temp=pd.DataFrame(pd.DataFrame(temp).to_records())
temp=temp.rename(columns={"0":"count"})
temp=temp.sort_values('count',ascending=False)
display(temp)

employer      bank  count
8          Google      HDFC     55
10         Google       SBI     55
14        Infosys       SBI     51
2        Flipkart       SBI     47
0        Flipkart      HDFC     46
17            TCS     ICICI     45
18            TCS       SBI     45
4   Goldman Sachs      HDFC     44
22         Zomato       SBI     44
16            TCS      HDFC     43
6   Goldman Sachs       SBI     42
7   Goldman Sachs  Yes Bank     42
11         Google  Yes Bank     42
13        Infosys     ICICI     42
5   Goldman Sachs     ICICI     40
1        Flipkart     ICICI     39
21         Zomato     ICICI     37
23         Zomato  Yes Bank     37
15        Infosys  Yes Bank     36
19            TCS  Yes Bank     35
3        Flipkart  Yes Bank     35
9          Google     ICICI     34
12        Infosys      HDFC     33
20         Zomato      HDFC     31

In [147]:
# Some more creativity
display(temp.drop_duplicates(subset=["employer"],keep="first"))

employer   bank  count
8          Google   HDFC     55
14        Infosys    SBI     51
2        Flipkart    SBI     47
17            TCS  ICICI     45
4   Goldman Sachs   HDFC     44
22         Zomato    SBI     44