In [10]:
# Q4.

import numpy as np

def factorial(n):
    prod = 1
    for i in range(2,n+1):
        prod *= i
    return prod

def prob_heads(n, k):
    if k>n:
        return 0
    
    fact = []
    for i in range(n+1):
        fact.append(factorial(i))
    
    prob = 0
    for i in range(k, n+1):
        prob += fact[n]/(fact[n-i]*fact[i])
    prob *= (0.5)**n
    return prob

prob_heads(10,1)


0.9990234375

In [19]:
# Q5

def total_binary(n):
    print("Total possible binary:", 2**n)
    
    ones = np.zeros(n+1)
    zeros = np.zeros(n+1)
    
    ones[1] = 1
    zeros[1] = 1
    
    for k in range(2, n+1):
        ones[k] = zeros[k-1]
        zeros[k] = zeros[k-1] + ones[k-1]
    
    return zeros[n]+ones[n]
    

total_binary(10)

Total possible binary: 1024


144.0

In [32]:
# Q1: Recurssion

def tot_ways(r, c):
    if r==1 or c==1:
        return 1
    return tot_ways(r,c-1)+tot_ways(r-1,c)

tot_ways(8,10)

11440

In [34]:
# Q1: DP

def tot_ways_eff(r,c):
    ways = np.zeros((r,c))
    ways[-1] = 1
    ways[:,0] = 1
    
    for rn in range(-2, -r-1, -1):
        for cn in range(1, c, 1):
            ways[rn, cn] = ways[rn+1, cn] + ways[rn, cn-1]
    #print(ways)
    return ways[0,-1]

tot_ways_eff(8,10)

11440.0

In [42]:
sample_path = np.array([[0,-1,0,0],
                       [-1,0,0,0],
                       [0,-1,0,0],
                       [0,0,0,0]])
print(sample_path)

[[ 0 -1  0  0]
 [-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0  0  0]]


In [43]:
# Q2: Recurssion

def ways_obs(path, r, c):
    if path[-1, 0] == -1:
        return 0
    if r==1 or c==1:
        if np.sum(path)==0:
            return 1
        else:
            return 0
    return ways_obs(path[:-1,:] ,r-1, c) + ways_obs(path[:,1:], r, c-1)

ways_obs(sample_path, 4,4)

4

In [46]:
# Q6

#N = amount
#S = coin values
#m = number of distinct coins

def create_change(n,s,m):
    if n==0:
        return 1
    if m<=0 and n>0:
        return 0
    if n<0:
        return 0
    return create_change(n,s[:-1],m-1) + create_change(n-s[-1],s, m)

In [48]:
create_change(10,[2,5,3,6], 4)

5