# Row Echelon Form


For a matrix to be considered as a RE (row echelon) form:
* All the rows having 0 should be at the bottom
* Leading entries of any row should be after (on right/in the next columns) the leading entry of the previous row

1  5  5
0  5  10
0  8  1

Not in RE form

1  5  5
0  5  10
0  0  1

1 4 5 9
0 9 8 8
0 0 0 1
0 0 0 0

# Reduced Row Echelon Form

The same as Row Echelon form with the only diffrence that the matrix is a diagnol matrix.

In [11]:
import numpy as np
A = np.random.randint(1,10,(3,3))*1.0
b = np.random.randint(1, 10, (3,1))*1.0

In [12]:
print(A)
print(b)

[[4. 7. 7.]
 [4. 6. 6.]
 [3. 1. 9.]]
[[5.]
 [1.]
 [6.]]


In [13]:
# Scale. Add. Swap. 

class EqSystem():
    def __init__(self, coeff, result):
        self.coeff = coeff
        self.res = result
        
    def swap(self, i, j):
        self.coeff[i], self.coeff[j] = self.coeff[j], self.coeff[i]
        self.res[i], self.res[j] = self.res[j], self.res[i]
        
    def scale(self, row, scale):
        self.coeff[row] *= scale
        self.res[row] *= scale
    
    def add(self, row1, row2, scale):
        self.coeff[row1] = self.coeff[row1] + scale*self.coeff[row2] 
        self.res[row1] = self.res[row1] + scale*self.res[row2]
        
    def stat(self):
        print(self.coeff)
        print(self.res)

In [19]:
eq = EqSystem(A.copy(), b.copy())

In [20]:
eq.stat()

[[4. 7. 7.]
 [4. 6. 6.]
 [3. 1. 9.]]
[[5.]
 [1.]
 [6.]]


In [21]:
eq.add(1 , 0, -1)

In [22]:
eq.stat()

[[ 4.  7.  7.]
 [ 0. -1. -1.]
 [ 3.  1.  9.]]
[[ 5.]
 [-4.]
 [ 6.]]


In [23]:
eq.add(2, 0, -(3/4))

In [24]:
eq.stat()

[[ 4.    7.    7.  ]
 [ 0.   -1.   -1.  ]
 [ 0.   -4.25  3.75]]
[[ 5.  ]
 [-4.  ]
 [ 2.25]]


In [25]:
eq.scale(1, -1)
eq.stat()

[[ 4.    7.    7.  ]
 [-0.    1.    1.  ]
 [ 0.   -4.25  3.75]]
[[5.  ]
 [4.  ]
 [2.25]]


In [26]:
eq.add(0, 1, -7)
eq.add(2, 1, 4.25)
eq.stat()

[[ 4.  0.  0.]
 [-0.  1.  1.]
 [ 0.  0.  8.]]
[[-23.  ]
 [  4.  ]
 [ 19.25]]


In [27]:
eq.scale(2, 1/8)
eq.stat()

[[ 4.  0.  0.]
 [-0.  1.  1.]
 [ 0.  0.  1.]]
[[-23.     ]
 [  4.     ]
 [  2.40625]]


In [28]:
eq.add(1, 2, -1)

In [29]:
eq.scale(0, 1/4)

In [30]:
eq.stat()

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
[[-5.75   ]
 [ 1.59375]
 [ 2.40625]]


In [31]:
print(A)
print(b)

[[4. 7. 7.]
 [4. 6. 6.]
 [3. 1. 9.]]
[[5.]
 [1.]
 [6.]]


In [34]:
def gaussian_elimination(eq, start_row, start_col):
    if start_row == eq.coeff.shape[0] or start_col == eq.coeff.shape[1]:
        return
    if eq.coeff[start_row, start_col] != 0:
        eq.scale(start_row, 1/eq.coeff[start_row, start_col])
        for row in range(eq.coeff.shape[0]):
            if row == start_row:
                continue
            eq.add(row, start_row, -1*eq.coeff[row, start_col])
        gaussian_elimination(eq, start_row+1, start_col+1)
    else:
        candidate_rows = np.argwhere(eq.coeff[start_row:, start_col] != 0)
        if len(candidate_rows) != 0:
            eq.swap(start_col, candidate_rows[0]+start_row)
            gaussian_elimination(eq, start_row, start_col)
        else:
            gaussian_elimination(eq, start_row, start_col+1)

In [42]:
eq = EqSystem(np.random.randint(1,10,(4,4))*1.0, np.random.randint(1,10,(4,1))*1.0)
gaussian_elimination(eq, 0, 0)

In [43]:
eq.stat()

[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[-0.72122762]
 [ 3.        ]
 [ 1.19693095]
 [-1.30434783]]


In [49]:
def determinant(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        return "Not Defined"
    if matrix.shape[0]==1:
        return matrix[0,0]
    
    det = 1
    
    if matrix[0,0] != 0:
        #matrix.scale(start_row, 1/matrix[0,0])
        det *= matrix[0,0]
        for row in range(1, matrix.shape[0]):
            #eq.add(row, start_row, -1*eq.coeff[row, start_col])
            det /= -matrix[row, 0]
        return det * determinant(matrix[1:, 1:])
    else:
        candidate_rows = np.argwhere(eq.coeff[start_row:, start_col] != 0)
        if len(candidate_rows) != 0:
            #eq.swap(start_col, candidate_rows[0]+start_row)
            det *= -1
            return det *  determinant(matrix[:,:])
        else:
            return det *  determinant(matrix[:,1:])
            #gaussian_elimination(eq, start_row, start_col+1)

In [50]:
determinant(A)

-18.0

In [51]:
np.linalg.det(A)

-32.0

In [52]:
A

array([[4., 7., 7.],
       [4., 6., 6.],
       [3., 1., 9.]])