# Numpy

> Reference Matrial: 
> https://numpy.org/devdocs/user/quickstart.html#advanced-indexing-and-index-tricks

### Assigning to arrays

In [2]:
import numpy as np
A=np.arange(1,28).reshape(3,3,3)

In [71]:
# You can assign an element
A[0][0][0]=-10
A[0,1,2] = -100
print(A)

[[[ -10    2    3]
  [   4    5 -100]
  [   7    8    9]]

 [[  10   11   12]
  [  13   14   15]
  [  16   17   18]]

 [[  19   20   21]
  [  22   23   24]
  [  25   26   27]]]


In [5]:
# You can also assign a subarray by slicing

# The value can be an array of the same shape
A[0,:,:]=np.arange(-9,0).reshape(3,3) # Equivalent to A[0]
A[1]=np.arange(-18,-9).reshape(3,3)
print(A)

[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-15 -14 -13]
  [-12 -11 -10]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]]]


In [7]:
# The value can be a constant
A[1,1,:]=-50
print(A)
print('*'*10)

[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-50 -50 -50]
  [-12 -11 -10]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]]]
**********


In [13]:
print(A[1])
print(A[0])
print(A[ [0,1] ])
print('-'*50)
print(A)

[[-18 -17 -16]
 [-50 -50 -50]
 [-12 -11 -10]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-50 -50 -50]
  [-12 -11 -10]]]
--------------------------------------------------
[[[ -9  -8  -7]
  [ -6  -5  -4]
  [ -3  -2  -1]]

 [[-18 -17 -16]
  [-50 -50 -50]
  [-12 -11 -10]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26  27]]]


In [29]:
# The value can also be a subarray that can be broadcasted
A=np.arange(1,28).reshape(3,3,3)

#A[2,:]=np.arange(1,4)
#A[[1,2]]=np.arange(1,4) #A[1] = np.ara  and A[2] = np.ara
A[[1,2], [0,1], :]=np.arange(1,4)
A[[0,2],[1,2],[0,1]] = -90000
A[[0,2],[1,2],2] = -9999
print(A)


[[[     1      2      3]
  [-90000      5  -9999]
  [     7      8      9]]

 [[     1      2      3]
  [    13     14     15]
  [    16     17     18]]

 [[    19     20     21]
  [     1      2      3]
  [    25 -90000  -9999]]]


In [41]:
a = np.arange(12)**2                       # the first 12 square numbers
print(a)
#i = np.array([1, 1, 3, 8, 5])              # an array of indices
#print(a[i])                                      # the elements of a at the positions i
#print(a[[3,4]])

j = np.array([[3, 4], [9, 7],[8,8],[8,8]])      # a bidimensional array of indices
print(a[j])                        # the same shape as j
print(a[j].shape)
print(a)
print(a.shape)


[  0   1   4   9  16  25  36  49  64  81 100 121]
[[ 9 16]
 [81 49]
 [64 64]
 [64 64]]
(4, 2)
[  0   1   4   9  16  25  36  49  64  81 100 121]
(12,)


### Integer Indexing

In [42]:
A=np.arange(1,65).reshape(4,4,4)

In [43]:
# You can index an array with a list/array of indices
print(A)
print(A[[0,1]])
print("\n"+"-_"*20+"\n")

# Just a single array indexes the first dimension, same as

print(A[[0,1],:,:])
print("\n"+"-_"*20+"\n")

# You can also index the other dimensions
print(A[:,:,[0,2]])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[[[ 1  3]
  [ 5  7]
  [ 9 11]
  [13 15]]

 [[17 19]
  [21 23]
  [25 27]
  [29 31]]

 [[33 35]
  [37 39]
  [41 43]
  [45 47]]

 [[49 51]
  [53 55]
  [57 59]
  [61 63]]]


In [44]:
# You can repeat an index in your array

print(A[[0,1,0,0,1],:,:])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]


In [54]:
# You can give a list of indexes for each dimension
print(A[[0,1,0,0],
        [1,2,2,2],
        [0,1,2,3]])

[ 5 26 11 12]


In [58]:
# The list of indices can be in a more complicated shape
print(A)
i=np.array([[0,1],[1,0]])
j=np.array([[1,2],[2,2]])
k=np.array(       [1,2])  #=> [[1,2],[1,2]]
A[i,j,k]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


array([[ 6, 27],
       [26, 11]])

In [65]:
# Shuffle an array
A=np.random.randint(1,20,10)
print(A)
shuffle=np.random.permutation(A.shape[0]) #np.random.shuffle(np.arange(number))
print(shuffle)
print(A[shuffle]) #np.random.shuffle(A)

[14 13  9  4 19  2  5 15 10 11]
[0 3 9 4 1 6 7 5 8 2]
[14  4 11 19 13  5 15  2 10  9]


In [66]:
# Sort an array according to another array

A=np.random.randint(1,20,10)
B=np.random.randint(1,20,10)

sorted_idcs=np.argsort(A)
B_sorted=B[sorted_idcs]

In [67]:
# You can also assign using integer indices

A=np.arange(1,28).reshape(3,3,3)
print(A)
A[[1,2],[0,2],2]=-50

print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  11 -50]
  [ 13  14  15]
  [ 16  17  18]]

 [[ 19  20  21]
  [ 22  23  24]
  [ 25  26 -50]]]


In [69]:
a = np.arange(12).reshape(3,4)
print(a)
print(a[[[0,1],[1,2]], [[2, 1],[3, 3]]])


i = np.array([[0, 1],[1, 2]])                     # indices for the first dim of a
              
j = np.array([[2, 1],[3, 3]])                     # indices for the second dim
              

print(a[i, j])                                   # i and j must have equal shape
print(a[i,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  5]
 [ 7 11]]
[[ 2  5]
 [ 7 11]]
[[ 2  6]
 [ 6 10]]


### Boolean Indexing

In [80]:
A=np.random.randint(1,50,12).reshape(3,4)
print(A)


[[45 13 45 31]
 [10 38 45 21]
 [ 8 42 48 13]]


In [81]:
# You can do slices or selections using boolean arrays same length as the dimension
# This is recommended to do only for one dimension

# selecting rows
#print(A[[True,True,True],:])
print("\n"+"-_"*20+"\n")

# selecting columns
#print(A[:,[True,False,False,True]])
print("\n"+"-_"*20+"\n")

# selecting both rows and columns is confusing
# and not recommended

print(A[[True,False,True],[True,False,False,True]])


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[45 13]


In [85]:
# Generally you'll use this in a more complicated way
# For example let's get the rows that have maximums > some value

A=np.random.randint(0,50,(4,6))
print(A)
print("\n"+"-_"*20+"\n")

maxes=np.max(A,axis=1)
print(maxes)
print(maxes>40)
print("\n"+"-_"*20+"\n")

print(A[maxes>40,:])

#np.where(condition, true_case, false_case)

[[ 1  9 44 25 10 32]
 [28 26 34 40  5  1]
 [27 25  0  0 42 29]
 [38  9 12 21 23 16]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[44 40 42 38]
[ True False  True False]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[[ 1  9 44 25 10 32]
 [27 25  0  0 42 29]]


In [87]:
# You can also index by a boolean array of the size as the 
# original
# It gives a flat array with all the entries that had True
print(A>10)
print(A[A>10])

[[False False  True  True False  True]
 [ True  True  True  True False False]
 [ True  True False False  True  True]
 [ True False  True  True  True  True]]
[44 25 32 28 26 34 40 27 25 42 29 38 12 21 23 16]


In [89]:
# Again you can use Boolean indexing to assign values

A=np.random.randint(0,50,(4,6))
print(A)
print("\n"+"-_"*20+"\n")
print(A[:,0])
A[A[:,0]<30]=np.arange(-6,0)
print(A)

[[32 40 33 13 25 37]
 [ 4 16 34 25 30 34]
 [ 2 26 47 30 34 19]
 [31 12 22 38 20 16]]

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[32  4  2 31]
[[32 40 33 13 25 37]
 [-6 -5 -4 -3 -2 -1]
 [-6 -5 -4 -3 -2 -1]
 [31 12 22 38 20 16]]


### np.inf, np.nan

In [92]:
# Numpy has a special type to represent infinity

print(np.inf)

# Actually regular python also has infinity

print(float("inf"))

inf
inf


In [94]:
# Let's see how np.inf behaves

# Multiplying by a negative number gives -np.inf
x=np.inf
print(x)
x*=-1
print(x)

# The opposite also works

x*=-5
print(x)

inf
-inf
inf


In [95]:
# Adding,subtracting,dividing,multiplying with normal
# numbers gives np.inf ( or -np.inf) except when multiplying
# or dividing with a negative number

print(np.inf+5)
print(-np.inf-6)
print(-np.inf*-30)
print(-np.inf/-22)

inf
-inf
inf
inf


In [97]:
# Dividing a number by np.inf gives 0

print(1223/np.inf)

0.0


In [98]:
# Interestingly dividing by 0 in numpy arrays gives infinity

print(np.array([222])/0)

[inf]


<ipython-input-98-067a3885ebda>:3: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([222])/0)


In [102]:
# What about operations between np.inf

# These have some meaning
print(np.inf + np.inf)
print(np.inf*np.inf)

# These are absolutely meaningless
print(np.inf-np.inf)
print(np.inf/np.inf)

inf
inf
nan
nan


In [103]:
# Which brings us to another special numpy data type
# nan : Not a Number
print(np.nan)

# Numpy uses nan to designate invalid values
# You can use it too

print(np.array([1,1,np.nan,2]))

nan
[ 1.  1. nan  2.]


In [105]:
# Some other ways you can get np.nan

print(np.sqrt(-2))
print(np.zeros(1)/np.zeros(1))
print(np.inf * 0)
print(np.log(-2))

nan
[nan]
nan
nan


<ipython-input-105-5512382ab81e>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-2))
<ipython-input-105-5512382ab81e>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.zeros(1)/np.zeros(1))
<ipython-input-105-5512382ab81e>:6: RuntimeWarning: invalid value encountered in log
  print(np.log(-2))


In [106]:
# Any operation with np.nan gives np.nan

print(1+np.nan)
print(np.inf + np.nan)
print(np.nan/np.array([0]))
print(np.nan - np.nan)

nan
nan
[nan]
nan


In [107]:
print(100/0)

ZeroDivisionError: division by zero

1. There might be some valid use cases for np.inf, but mostly you will encounter it when some calculation error happens - similar to division by zero.
2. If you see np.nan then clearly some undefined arithmetic operation has happened in your code. 